name: I am Reviewed 🚀
run-name: ${{ github.actor }} is doing a code review
on: [pull_request]

permissions:
  pull-requests: write  # Required for posting comments
  contents: read        # Required for checking out code

jobs:
  code_review:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CLOUD_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "🔎 PR Number ${{ github.event.pull_request.number }}."

      - id: do-a-review
        uses: darkin100/i-am-reviewed@v1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}
          repository: ${{ github.repository }}
          google-cloud-project: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          google-cloud-location: ${{ secrets.GOOGLE_CLOUD_LOCATION }}
          google-cloud-credentials: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
        

